<a href="https://colab.research.google.com/github/NurFortuna/Deep_Learning_with_Tensorflow_notes/blob/main/RBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!pip install tensorflow==2.2.0
!pip install pillow==8.1.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
import tensorflow as tf
import numpy as np

from PIL import Image
import matplotlib.pyplot as plt
%matplotlib inline

Restricted Boltzmann Machines(RBM) have two layers. First layer is called the visible layer and second layer is the hidden layer. In this example is V = 7 and H = 2 for bias

In [10]:
v_bias = tf.Variable(tf.zeros([7]), tf.float32)
h_bias = tf.Variable(tf.zeros([2]), tf.float32)

We have to define weights among the input layer and hidden layer nodes. Visible layer(V) = 7 and Hidden layer(H) = 2 so W(weight) of shape (7,2)

In [11]:
W = tf.constant(np.random.normal(loc=0.0, scale=1.0, size=(7, 2)).astype(np.float32))

In [12]:
#forward
X = tf.constant([[1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]], tf.float32)

v_state = X
print ("Input: ", v_state)

h_bias = tf.constant([0.1, 0.1])
print ("hb: ", h_bias)
print ("w: ", W)

# Calculate the probabilities of turning the hidden units on:
h_prob = tf.nn.sigmoid(tf.matmul(v_state, W) + h_bias)  #probabilities of the hidden units
print ("p(h|v): ", h_prob)

#The tf.randomUniform()->function is used to create a tf.Tensor with values sampled from a uniform distribution.
#tf.sign()->Returns an element-wise indication of the sign of a number.

# Draw samples from the distribution:
h_state = tf.nn.relu(tf.sign(h_prob - tf.random.uniform(tf.shape(h_prob)))) #states
print ("h0 states:", h_state)

Input:  tf.Tensor([[1. 0. 0. 1. 0. 0. 0.]], shape=(1, 7), dtype=float32)
hb:  tf.Tensor([0.1 0.1], shape=(2,), dtype=float32)
w:  tf.Tensor(
[[ 0.38531688  0.9174644 ]
 [-0.5533306  -0.9534142 ]
 [ 0.29113623  1.2777803 ]
 [-1.2913742  -0.85300493]
 [ 0.43873632  0.65792054]
 [-0.23343347  1.4243189 ]
 [ 0.7496359   0.38295138]], shape=(7, 2), dtype=float32)
p(h|v):  tf.Tensor([[0.3087313 0.5410224]], shape=(1, 2), dtype=float32)
h0 states: tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)


In [13]:
#backward
#Backward pass: This step, the data that is passed backward is 
#also combined with the same weights and overall bias.
vb = tf.constant([0.1, 0.2, 0.1, 0.1, 0.1, 0.2, 0.1])
print ("b: ", vb)

v_prob = tf.nn.sigmoid(tf.matmul(h_state, tf.transpose(W)) + vb)
print ("p(vi∣h): ", v_prob)

v_state = tf.nn.relu(tf.sign(v_prob - tf.random.uniform(tf.shape(v_prob))))
print ("v probability states: ", v_state)

b:  tf.Tensor([0.1 0.2 0.1 0.1 0.1 0.2 0.1], shape=(7,), dtype=float32)
p(vi∣h):  tf.Tensor(
[[0.5249792  0.54983395 0.5249792  0.5249792  0.5249792  0.54983395
  0.5249792 ]], shape=(1, 7), dtype=float32)
v probability states:  tf.Tensor([[0. 0. 0. 0. 0. 1. 1.]], shape=(1, 7), dtype=float32)


In [14]:
inp = X
print("input X:" , inp.numpy())

print("probablity vector:" , v_prob[0].numpy())
v_probability = 1

for elm, p in zip(inp[0],v_prob[0]) :
    if elm ==1:
        v_probability *= p
    else:
        v_probability *= (1-p)

print("probability of generating X: " , v_probability.numpy())

input X: [[1. 0. 0. 1. 0. 0. 0.]]
probablity vector: [0.5249792  0.54983395 0.5249792  0.5249792  0.5249792  0.54983395
 0.5249792 ]
probability of generating X:  0.0059864256
