<a href="https://colab.research.google.com/github/NurFortuna/Deep_Learning_with_Tensorflow_notes/blob/main/tensorflow_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Installing TensorFlow
!pip install grpcio==1.24.3
!pip install tensorflow==2.2.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 70.0 MB/s eta 0:00:00
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.51.1
    Uninstalling grpcio-1.51.1:
      Successfully uninstalled grpcio-1.51.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
grpcio-status 1.48.2 requires grpcio>=1.48.2, but you have grpcio 1.24.3 which is incompatible.
google-cloud-bigquery 3.4.1 requires grpcio<2.0dev,>=1.47.0, but you have grpcio 1.24.3 which is incompatible.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 516.3/516.3 MB 3.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.0/26.0 MB 76.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━

In [ ]:
#Importing TensorFlow
import tensorflow as tf
if not tf.__version__ == '2.2.0':
    print(tf.__version__)
    raise ValueError('please upgrade to TensorFlow 2.2.0, or restart your Kernel (Kernel->Restart & Clear Output)')

Now we call the TensorFlow functions that construct new tf.Operation and tf.Tensor objects. As mentioned, each tf.Operation is a node and each tf.Tensor is an edge in the graph.

Lets add 2 constants to our graph. For example, calling tf.constant([2], name = 'constant_a') adds a single tf.Operation to the default graph. This operation produces the value 2, and returns a tf.Tensor that represents the value of the constant.
Notice: tf.constant([2], name="constant_a") creates a new tf.Operation named "constant_a" and returns a tf.Tensor named "constant_a:0".

In [ ]:
#tf.function and AutoGraph

a = tf.constant([2], name = 'constant_a')
b = tf.constant([3], name = 'constant_b')

In [ ]:
a

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

In [ ]:
tf.print(a.numpy()[0])

2


In [ ]:
@tf.function
def add(a,b):
    c = tf.add(a, b)
    #c = a + b is also a way to define the sum of the terms
    print(c)
    return c


In [ ]:
result = add(a,b)
tf.print(result[0])


Tensor("Add:0", shape=(1,), dtype=int32)
5


In [ ]:
#Defining multidimensional arrays using TensorFlow

In [ ]:
Scalar = tf.constant(2)
print('Scalar (1 entry) \n %s \n' % Scalar)

Scalar (1 entry) 
 tf.Tensor(2, shape=(), dtype=int32) 



In [ ]:
Vector = tf.constant([5,6,2])
print('Vector (3 entries) \n %s \n' % Vector)

Vector (3 entries) 
 tf.Tensor([5 6 2], shape=(3,), dtype=int32) 



In [ ]:
Matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix (3x3 entries) \n %s \n' % Matrix)

Matrix (3x3 entries) 
 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32) 



In [ ]:
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
print ("Tensor (3x3x3 entries) :\n %s \n" % Tensor)

Tensor (3x3x3 entries) :
 tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]], shape=(3, 3, 3), dtype=int32) 



In [ ]:
Scalar.shape

TensorShape([])

In [ ]:
Tensor.shape

TensorShape([3, 3, 3])

In [ ]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

In [ ]:
@tf.function
def add():
    add_1_operation = tf.add(Matrix_one, Matrix_two)
    return add_1_operation

In [ ]:
print ("Defined using tensorflow function :")
add_1_operation = add()
print(add_1_operation)
print ("Defined using normal expressions :")
add_2_operation = Matrix_one + Matrix_two
print(add_2_operation)

Defined using tensorflow function :
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)
Defined using normal expressions :
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [ ]:
@tf.function
def sub():
  sub_1_operation = tf.subtract(Matrix_one,Matrix_two)
  return sub_1_operation

In [ ]:
sub_1_operation = sub()
print(sub_1_operation)

sub_1_operation = Matrix_one - Matrix_two
print(sub_1_operation)

tf.Tensor(
[[-1  0  1]
 [ 0  1  2]
 [ 1  2  3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[-1  0  1]
 [ 0  1  2]
 [ 1  2  3]], shape=(3, 3), dtype=int32)


In [ ]:
#The tf.matMul() function is used to compute the dot product of two matrices, A * B.

In [ ]:
Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_two = tf.constant([[2,3],[3,4]])

In [ ]:
@tf.function
def mathmul():
  return tf.matmul(Matrix_one, Matrix_two)

In [ ]:

mul_operation = mathmul()

print ("Defined using tensorflow function :")
print(mul_operation)

Defined using tensorflow function :
tf.Tensor(
[[13 18]
 [18 25]], shape=(2, 2), dtype=int32)


In [ ]:
v = tf.Variable(0)

We now create a python method increment_by_one. This method will internally call td.add that takes in two arguments, the reference_variable to update, and assign it to the value_to_update it by.

In [ ]:
@tf.function
def increment_by_one(v):
        v = tf.add(v,1)
        return v

To update the value of the variable v, we simply call the increment_by_one method and pass the variable to it. We will invoke this method thrice. This method will increment the variable by one and print the updated value each time.

In [ ]:
for i in range(3):
    v = increment_by_one(v)
    print(v)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


Operations

In [ ]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)
print ('c =: %s' % c)
print ('d =: %s' % d)


c =: tf.Tensor([7], shape=(1,), dtype=int32)
d =: tf.Tensor([3], shape=(1,), dtype=int32)
